### ISSUE TITLE
Support for deepseq 1.4

### ISSUE THREAD

**Issue by snoyberg** [ekmett/compensated#5]
Can you relax the upper bound on deepseq to allow 1.4, which ships with GHC 7.10? Necessary to ship Stackage with GHC 7.10.

**Comment by claudeha** [comment]
I'd appreciate this too (I'm working on `exp-extended` which extends the exponent range of `RealFloat` types, I want it to be possible to use it with `compensated` but it's not installable by default).

In case it helps, I used `cabal install --allow-newer`, seems to work ok in my (admittedly brief) tests, here's my output from `cabal exec -- ghc-pkg list`:

    /home/claude/opt/lib/ghc-7.10.1/package.conf.d:
        Cabal-1.22.2.0
        array-0.5.1.0
        base-4.8.0.0
        bin-package-db-0.0.0.0
        binary-0.7.3.0
        rts-1.0
        bytestring-0.10.6.0
        containers-0.5.6.2
        deepseq-1.4.1.1
        directory-1.2.2.0
        filepath-1.4.0.0
        (ghc-7.10.1)
        ghc-prim-0.4.0.0
        haskeline-0.7.2.1
        hoopl-3.10.0.2
        hpc-0.6.0.2
        integer-gmp-1.0.0.0
        pretty-1.1.2.0
        process-1.2.3.0
        template-haskell-2.10.0.0
        terminfo-0.4.0.1
        time-1.5.0.1
        transformers-0.4.2.0
        unix-2.7.1.0
        xhtml-3000.2.1
    
    /home/claude/code/local/exp-extended/.cabal-sandbox/x86_64-linux-ghc-7.10.1-packages.conf.d:
        StateVar-1.1.0.0
        adjunctions-4.2.1
        base-orphans-0.3.2
        bifunctors-5
        bytes-0.15
        cereal-0.4.1.1
        comonad-4.2.6
        compensated-0.6.1
        contravariant-1.3.1.1
        distributive-0.4.4
        exceptions-0.8.0.2
        exp-extended-0.1.0.0
        free-4.12.1
        generic-deriving-1.7.0
        hashable-1.2.3.2
        hashable-extras-0.2.1
        kan-extensions-4.2.2
        lens-4.11
        log-domain-0.10.1
        mtl-2.2.1
        nats-1
        old-locale-1.0.0.7
        old-time-1.1.0.3
        parallel-3.2.0.6
        prelude-extras-0.4
        primitive-0.6
        profunctors-5.1.1
        reflection-1.5.2.1
        safecopy-0.8.5
        semigroupoids-5.0.0.1
        semigroups-0.16.2.2
        stm-2.4.4
        tagged-0.8.0.1
        text-1.2.1.1
        transformers-compat-0.4.0.4
        unordered-containers-0.2.5.1
        vector-0.10.12.3
        void-0.7

**Comment by wyager** [comment]
+1

**Comment by DanBurton** [comment]
This appears to be done.

**Comment by RyanGlScott** [comment]
Fixed in [`compensated-0.7.1`](http://hackage.haskell.org/package/compensated-0.7.1).
