### ISSUE TITLE
Support for generic-deriving-1.9

### ISSUE THREAD

**Issue by DanBurton** [ekmett/compensated#7]
Current bounds are < 1.9.

**Comment by claudeha** [comment]
generic-deriving on hackage is now at 1.10.4.1

**Comment by claudeha** [comment]
safecopy-0.9.1 and binary-0.8.4.0 also could do with bounds bumps, compiled fineon ghc-8.0.1 with --allow-newer but I haven't tested the built results

**Comment by RyanGlScott** [comment]
Fixed in [`compensated-0.7.1`](http://hackage.haskell.org/package/compensated-0.7.1).
